[package]
name = "osc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "phs"
path = "src/phs/main.rs"

[[bin]]
name = "terrain"
path = "src/terrain/main.rs"

[dependencies]
jack = "0.11.3"